### ISSUE TITLE
Git issue when composer.json is not in root directory

### ISSUE THREAD

**Issue by mgalang** [wunderio/code-quality-old#13]
An error will occur if composer.json is not in root directory: `Error: No git repo!`

**Comment by ragnarkurmwunder** [comment]
Should not happen anymore.
Composer can be now installed into arbitrary subfolder under git repo.
The test in `tests/` confirms that.
Test needs to be used with `-c arbitrary/sub/folder/path/for/composer`.

**Comment by ragnarkurmwunder** [comment]
Actually that concerned only `install-update.sh`, but not the hook itself.

**Comment by ragnarkurmwunder** [comment]
Ok, refactored pre-commit to work with arbitrary composer location.
Composer location is derived from pre-commit hook link.
